const ENEMIES = {
    'Slime': {
      name: 'Slime',
      strength: 5,
      agility: 3,
      hp: 3,
    },
    'Red Slime': {
      name: 'Red Slime',
      strength: 7,
      agility: 3,
      hp: 3,
    },
    'Drakee': {
      name: 'Drakee',
      strength: 9,
      agility: 6,
      hp: [5, 6],
    },
    'Ghost': {
      name: 'Ghost',
      strength: 11,
      agility: 8,
      hp: [6, 7],
    },
    'Magician': {
      name: 'Magician',
      strength: 11,
      agility: 12,
      hp: [10, 13],
    },
    'Magidrakee': {
      name: 'Magidrakee',
      strength: 14,
      agility: 14,
      hp: [12, 15],
    },
    'Scorpion': { // Incomplete
      name: 'Scorpion',
      strength: 18,
      agility: 16,
      hp: [16, 20],
    },
    'Druin': {
      name: 'Druin',
      strength: 20,
      agility: 18,
      hp: [17, 22],
    },
    'Poltergeist': {
      name: 'Poltergeist',
      strength: 18,
      agility: 20,
      hp: [18, 23],
    },
    'Droll': {
      name: 'Droll',
      strength: 24,
      agility: 24,
      hp: [19, 25],
    },
    'Drakeema': {
      name: 'Drakeema',
      strength: 22,
      agility: 26,
      hp: [16, 20],
    },
    'Skeleton': {
      name: 'Skeleton',
      strength: 28,
      agility: 22,
      hp: [16, 20],
    },
    'Warlock': {
      name: 'Warlock',
      strength: 28,
      agility: 22,
      hp: [23, 30],
    },
    'Metal Scorpion': {
      name: 'Metal Scorpion',
      strength: 36,
      agility: 42,
      hp: [17, 22],
    },
    'Wolf': {
      name: 'Wolf',
      strength: 40,
      agility: 30,
      hp: [26, 34],
    },
    'Wraith': {
      name: 'Wraith',
      strength: 44,
      agility: 34,
      hp: [26, 34],
    },
    'Metal Slime': {
      name: 'Metal Slime',
      strength: 10,
      agility: 255,
      hp: 4,
    },
    'Specter': {
      name: 'Specter',
      strength: 40,
      agility: 38,
      hp: [28, 36],
    },
    'Wolflord': {
      name: 'Wolflord',
      strength: 50,
      agility: 36,
      hp: [29, 38],
    },
    'Druinlord': {
      name: 'Druinlord',
      strength: 47,
      agility: 40,
      hp: [27, 35],
    },
    'Drollmagi': {
      name: 'Drollmagi',
      strength: 52,
      agility: 50,
      hp: [29, 38],
    },
    'Wyvern': {
      name: 'Wyvern',
      strength: 56,
      agility: 48,
      hp: [32, 42],
    },
    'Rogue Scorpion': {
      name: 'Rogue Scorpion',
      strength: 60,
      agility: 90,
      hp: [27, 35],
    },
    'Wraith Knight': {
      name: 'Wraith Knight',
      strength: 68,
      agility: 56,
      hp: [35, 46],
    },
    'Golem': {
      name: 'Golem',
      strength: 120,
      agility: 60,
      hp: [53, 70],
    },
    'Goldman': {
      name: 'Goldman',
      strength: 48,
      agility: 40,
      hp: [38, 50],
    },
    'Knight': {
      name: 'Knight',
      strength: 76,
      agility: 78,
      hp: [42, 55],
    },
    'Magiwyvern': {
      name: 'Magiwyvern',
      strength: 78,
      agility: 68,
      hp: [44, 58],
    },
    'Demon Knight': {
      name: 'Demon Knight',
      strength: 79,
      agility: 64,
      hp: [38, 50],
    },
    'Werewolf': {
      name: 'Werewolf',
      strength: 86,
      agility: 70,
      hp: [46, 60],
    },
    'Green Dragon': {
      name: 'Green Dragon',
      strength: 88,
      agility: 74,
      hp: [49, 65],
    },
    'Starwyvern': {
      name: 'Starwyvern',
      strength: 86,
      agility: 80,
      hp: [49, 65],
    },
    'Wizard': {
      name: 'Wizard',
      strength: 80,
      agility: 70,
      hp: [49, 65],
    },
    'Axe Knight': {
      name: 'Axe Knight',
      strength: 94,
      agility: 82,
      hp: [53, 70],
    },
    'Blue Dragon': {
      name: 'Blue Dragon',
      strength: 98,
      agility: 84,
      hp: [53, 70],
    },
    'Stoneman': {
      name: 'Stoneman',
      strength: 100,
      agility: 40,
      hp: [121, 160],
    },
    'Armored Knight': {
      name: 'Armored Knight',
      strength: 105,
      agility: 86,
      hp: [68, 90],
    },
    'Red Dragon': {
      name: 'Red Dragon',
      strength: 120,
      agility: 90,
      hp: [76, 100],
    },
    'Dragonlord (first form)': {
      name: 'Dragonlord (first form)',
      strength: 90,
      agility: 75,
      hp: [76, 100],
    },
    'Dragonlord (second form)': {
      name: 'Dragonlord (second form)',
      strength: 140,
      agility: 200,
      hp: 130,
    },
  }

export function changeEnemy(msg) {
  const newEnemy = ENEMIES[msg.enemy];
  return newEnemy;
};
